version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-node-browsers'
    working_directory: ~/pet_book
    steps:
      - checkout
      - run: 
          name: Install CLI
          command: npm install @angular/cli
      - run:
          name: Install dependencies and build project
          command: npm install & npm build --skip-test
      - run:
          name: Run unit test
          command: npm test
      - sonarcloud/scan
  deploy:
    machine:
        enabled: true
    working_directory: ~/pet_book
    steps:     
      - aws-s3/sync:
          arguments: |
            --dry-run --acl public-read \
            --cache-control "max-age=86400"          
          overwrite: true
          aws-region: us-west-1
          from: pet_book
          to: 's3://pet-book-project'
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  aws-s3: circleci/aws-s3@1.0.15

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
      - deploy:
          requires:
              - build
          
