version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/openjdk:8-node-browsers'
    working_directory: ~/pet_book
    steps:
      - checkout
      - run: 
          name: Install CLI
          command: npm install @angular/cli
      - run:
          name: Install dependencies and build project
          command: npm install 
      - run:
          name: Build Project
          command: npm build
      - run:
          name: Run unit test
          command: npm test-ci
      - sonarcloud/scan
      - aws-s3/sync:             
          overwrite: true
          from: ~/pet_book/dist
          to: 's3://pet-book-project'
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
  aws-s3: circleci/aws-s3@1.0.15

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
          
